services:
  db:
    image: postgres
    restart: always
    container_name: storage_database
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker_net
  
  main:
    image: storage
    restart: always
    container_name: storage_main
    ports:
      - 8080:8080
    networks:
      - docker_net
    environment:
      DB_URL: "storage_database"
    depends_on:
      - db

  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge

volumes:
  pgdata: